<?php

/**
 * @author            ${author.name} (${author.email})
 * @website           ${author.url}
 * @copyright         ${copyrights}
 * @license           ${license.url} ${license.name}
 * @package           ${package}
 * @subpackage        ${subpackage}
 */

use BPExtensions\Component\BPGallery\Administrator\Helper\BPGalleryHelper;
use BPExtensions\Component\BPGallery\Site\Helper\LayoutHelper;
use BPExtensions\Component\BPGallery\Site\View\Image\HtmlView;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Multilanguage;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\Registry\Registry;

defined('_JEXEC') or die;
/**
 * @var Registry $params
 * @var HtmlView $this
 */

// Include assets generated by Webpack
if ($this->params->def('include_component_assets', 1)) {
    LayoutHelper::includeEntryPointAssets('component');
}
if ($this->params->def('include_theme_assets', 1)) {
    LayoutHelper::includeEntryPointAssets('image-default');
}
if ($this->params->def('images_lightbox', 1)) {
    $lightboxLayoutData = [
        'params'         => $this->params,
        'lightbox_query' => '.bpgallery-image-page'
    ];
    (new FileLayout('bpgallery.lightbox', JPATH_ROOT))->render($lightboxLayoutData);
}

// Create shortcuts to some parameters.
$params = $this->params;
$canEdit = $params->get('access-edit');
$user = $this->user;

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Multilanguage::isEnabled() && $params->get('show_associations'));

$image_lightbox = $this->params->get('images_lightbox', 1);

$url_full = BPGalleryHelper::getThumbnail($this->item, 1920, 0, BPGalleryHelper::METHOD_FIT_WIDTH);

?>
<article class="bpgallery-image-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Thing">
    <meta itemprop="inLanguage"
          content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>"/>
    <?php if ($this->params->get('show_page_heading')) : ?>
        <div class="page-header">
            <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
        </div>
    <?php endif ?>

    <?php if ($params->get('show_title')) : ?>
        <div class="page-header">
            <h2 itemprop="headline">
                <?php echo $this->escape($this->item->title); ?>
            </h2>
            <?php if ($this->item->state == 0) : ?>
                <span class="label label-warning"><?php echo Text::_('JUNPUBLISHED'); ?></span>
            <?php endif; ?>
            <?php if (strtotime($this->item->publish_up) > strtotime(Factory::getDate())) : ?>
                <span class="label label-warning"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
            <?php endif; ?>
            <?php if ((!empty($this->item->publish_down) && strtotime($this->item->publish_down) < strtotime(Factory::getDate())) && $this->item->publish_down !== null) : ?>
                <span class="label label-warning"><?php echo Text::_('JEXPIRED'); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php echo (new FileLayout('info.block'))->render(['item'     => $this->item,
                                                       'params'   => $params,
                                                       'position' => 'above'
    ]); ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php if ($image_lightbox): ?>
        <a href="<?php echo $url_full ?>" target="_blank" class="image-link" title="<?php echo $this->item->title ?>">
            <img src="<?php echo $url_full ?>" alt="<?php echo $this->item->title ?>" class="image"/>
        </a>
    <?php else: ?>
        <img src="<?php echo $url_full ?>" alt="<?php echo $this->item->title ?>" class="image"/>
    <?php endif ?>

    <div itemprop="descripion">
        <?php echo $this->item->text; ?>
    </div>

    <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</article>
