<?php

/**
 * @author        ${author.name} (${author.email})
 * @website        ${author.url}
 * @copyright    ${copyrights}
 * @license        ${license.url} ${license.name}
 * @package        ${package}
 * @subpackage        ${subpackage}
 */

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;

defined('_JEXEC') or die;

// Include assets generated by Webpack
if ($this->params->def('include_component_assets', 1)) {
    BPGalleryHelperLayout::includeEntryPointAssets('component');
}
if ($this->params->def('include_theme_assets', 1)) {
    BPGalleryHelperLayout::includeEntryPointAssets('category-default');
}
if ($this->params->def('image_lightbox', 1)) {
    HTMLHelper::_('jquery.framework');
    BPGalleryHelperLayout::includeEntryPointAssets('lightbox');

    $lightbox_options = [
        'type' => 'image',
        'gallery' => [
            'enabled' => true,
            'tCounter' => '<span class="mfp-counter">' . Text::_('COM_BPGALLERY_LIGHTBOX_N_OF_X') . '</span>',
            'tPrev' => Text::_('COM_BPGALLERY_LIGHTBOX_PREV'),
            'tNext' => Text::_('COM_BPGALLERY_LIGHTBOX_NEXT'),
            'tClose' => Text::_('COM_BPGALLERY_LIGHTBOX_CLOSE'),
        ],
        'closeBtnInside' => true,
        'zoom' => [
            'enabled' => true,
            'duration' => 300,
            'easing' => 'ease-in-out'
        ]
    ];
    $lightbox_options = json_encode($lightbox_options);

    $this->document->addScriptDeclaration("
        // Run lightbox for BP Gallery
        jQuery(function($){
            var lightbox_options = $lightbox_options;
            lightbox_options.disableOn = function(){
                if( $(window).width() < 600 ) {
                    return false;
                }
                return true;
            }
            lightbox_options.zoom.opener = function(openerElement) {
                return openerElement.is('img') ? openerElement : openerElement.find('img');
            }
            $('.bpgallery-category .image-link').magnificPopup(lightbox_options);
        });
    ");
}

$this->subtemplatename = 'items';
echo JLayoutHelper::render('joomla.content.category_default', $this);
