<?php

/**
 * @author        ${author.name} (${author.email})
 * @website        ${author.url}
 * @copyright    ${copyrights}
 * @license        ${license.url} ${license.name}
 * @package        ${package}
 * @subpackage        ${subpackage}
 */

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\Registry\Registry;

defined('_JEXEC') or die;

/**
 * @var Registry $params
 */
$params = $this->params;

HTMLHelper::_('jquery.framework');

// Include assets generated by Webpack
if ($params->def('include_component_assets', 1)) {
    BPGalleryHelperLayout::includeEntryPointAssets('masonry');
}
if ($params->def('include_theme_assets', 1)) {
    BPGalleryHelperLayout::includeEntryPointAssets('category-default');
}

$this->document->addScriptDeclaration("
    // Run Masonry Layout
    jQuery(function($){
        var gallery = $('.bpgallery-category-masonry .items').masonry({
          
        });
        
        // Reload Masonry on image loaded event
        gallery.imagesLoaded().progress( function() {
            gallery.masonry('layout');
        });
    });
");

if ($params->def('images_lightbox', 1)) {
    BPGalleryHelperLayout::includeEntryPointAssets('lightbox');

    $lightbox_options = [
        'type' => 'image',
        'image' => (object)[],
        'gallery' => [
            'enabled' => true,
            'tCounter' => '<span class="mfp-counter">' . Text::_('COM_BPGALLERY_LIGHTBOX_N_OF_X') . '</span>',
            'tPrev' => Text::_('COM_BPGALLERY_LIGHTBOX_PREV'),
            'tNext' => Text::_('COM_BPGALLERY_LIGHTBOX_NEXT'),
        ],
        'tClose' => Text::_('COM_BPGALLERY_LIGHTBOX_CLOSE'),
        'closeBtnInside' => true,
        'zoom' => [
            'enabled' => true,
            'duration' => 300,
            'easing' => 'ease-in-out'
        ]
    ];

    $lightbox_options = json_encode($lightbox_options);

    // Enable or disable image title in a lightbox
    $titleSrc = '"title"';
    if (!$params->get('images_lightbox_title', 1)) {
        $titleSrc = "function(){return ''}";
    }

    // Disable lightbox below given screen width
    $disableOn = '';
    $images_lightbox_min_res = $params->get('images_lightbox_min_res', 0);
    if ($images_lightbox_min_res) {
        $disableOn = "lightbox_options.disableOn = function(){
                if( $(window).width() < $images_lightbox_min_res ) {
                    return false;
                }
                return true;
            }";
    }

    $this->document->addScriptDeclaration("
        // Run lightbox for BP Gallery
        jQuery(function($){
            var lightbox_options = $lightbox_options;
            $disableOn
            lightbox_options.image.titleSrc = $titleSrc;
            lightbox_options.zoom.opener = function(openerElement) {
                return openerElement.is('img') ? openerElement : openerElement.find('img');
            }
            $('.bpgallery-category .image-link').magnificPopup(lightbox_options);
        });
    ");
}

$category = $this->get('category');
$canEdit = $params->get('access-edit');

$dispatcher = JEventDispatcher::getInstance();

$category->text = $category->description;
$dispatcher->trigger('onContentPrepare', array('com_bpgallery.categories', &$category, &$params, 0));
$category->description = $category->text;

$results = $dispatcher->trigger('onContentAfterTitle', array('com_bpgallery.categories', &$category, &$params, 0));
$afterDisplayTitle = trim(implode("\n", $results));

$results = $dispatcher->trigger('onContentBeforeDisplay', array('com_bpgallery.categories', &$category, &$params, 0));
$beforeDisplayContent = trim(implode("\n", $results));

$results = $dispatcher->trigger('onContentAfterDisplay', array('com_bpgallery.categories', &$category, &$params, 0));
$afterDisplayContent = trim(implode("\n", $results));
?>
<section class="bpgallery-category bpgallery-category-masonry<?php echo $this->pageclass_sfx ?>">

    <div class="page-header">
        <?php if ($params->get('show_page_heading')) : ?>
            <h1>
                <?php echo $this->escape($params->get('page_heading')); ?>
            </h1>
        <?php endif; ?>

        <?php if ($params->get('show_category_title', 1)) : ?>
            <h2>
                <?php echo JHtml::_('content.prepare', $category->title, '', 'com_bpgallery.category.title'); ?>
            </h2>
        <?php endif; ?>
    </div>

    <?php echo $afterDisplayTitle; ?>

    <?php if ($beforeDisplayContent || $afterDisplayContent || $params->get('show_description', 1) || $params->def('show_description_image', 1)) : ?>
        <div class="category-desc">
            <?php if ($params->get('show_description_image') && $category->getParams()->get('image')) : ?>
                <img src="<?php echo $category->getParams()->get('image'); ?>"
                     alt="<?php echo htmlspecialchars($category->getParams()->get('image_alt'), ENT_COMPAT, 'UTF-8'); ?>"/>
            <?php endif; ?>
            <?php echo $beforeDisplayContent; ?>
            <?php if ($params->get('show_description') && $category->description) : ?>
                <?php echo JHtml::_('content.prepare', $category->description, '', 'com_bpgallery.category.description'); ?>
            <?php endif; ?>
            <?php echo $afterDisplayContent; ?>
            <div class="clr"></div>
        </div>
    <?php endif; ?>

    <?php echo $this->loadTemplate('items') ?>

    <?php if ($this->maxLevel != 0 && $this->get('children')) : ?>
        <div class="cat-children">
            <?php if ($params->get('show_category_heading_title_text', 1) == 1) : ?>
                <h3>
                    <?php echo JText::_('JGLOBAL_SUBCATEGORIES'); ?>
                </h3>
            <?php endif; ?>
            <?php echo $this->loadTemplate('children'); ?>
        </div>
    <?php endif; ?>

</section>
